<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NdeipiChat.SubApps.Sdk\NdeipiChat.SubApps.Sdk.csproj" />
    <ProjectReference Include="..\NdeipiChat.Contracts\NdeipiChat.Contracts.csproj" />
  </ItemGroup>

</Project>
